const { query } = require("../config/db");
const ensureBlogTables = require("../utils/ensureBlogTables");
const slugify = require("../utils/slugify");
const {
  POST_TABLES,
  getPostTableForCategory,
  parseScopedPostId,
  scopedPostId,
  unionPostSelect,
} = require("../utils/contentTables");
const {
  computeSeoQuality,
  generateFinalSeo,
  shouldBlockPublishForSeo,
} = require("../utils/seoQuality");
const fs = require("fs");
const path = require("path");
const VALID_SECTIONS = new Set([
  "featured",
  "editor",
  "latest",
  "analytics",
  "guides",
  "reports",
  "insights",
  "archive",
]);

const buildImageUrl = (req, imagePath) => {
  if (!imagePath) {
    return "";
  }

  if (/^https?:\/\//i.test(imagePath)) {
    return imagePath;
  }

  const normalizedPath = imagePath.replace(/\\/g, "/");
  return `${req.protocol}://${req.get("host")}${normalizedPath.startsWith("/") ? "" : "/"}${normalizedPath}`;
};

const asString = (value, fallback = "") =>
  value === undefined || value === null ? fallback : String(value);

const parseJsonValue = (value, fallback = null) => {
  if (!value) {
    return fallback;
  }

  if (typeof value === "object") {
    return value;
  }

  try {
    return JSON.parse(value);
  } catch (_error) {
    return fallback;
  }
};

const mapPost = (req, row) => {
  const finalSeo = generateFinalSeo(row);
  const computedSeoQuality = computeSeoQuality(row, { finalSeo });
  const storedSeoBreakdown = parseJsonValue(row.seo_breakdown);
  const seoBreakdown = storedSeoBreakdown || computedSeoQuality;

  return {
    id: row.source_table ? scopedPostId(row.source_table, row.id) : row.id,
    numericId: row.id,
    sourceTable: row.source_table || "posts",
    title: row.title,
    slug: row.slug,
    category: row.category,
    subcategory: row.subcategory || "",
    content: row.content,
    image: buildImageUrl(req, row.image),
    imagePath: row.image || "",
    tags: row.tags
      ? row.tags
          .split(",")
          .map((tag) => tag.trim())
          .filter(Boolean)
      : [],
    status: row.status,
    featured: Boolean(row.featured),
    section: VALID_SECTIONS.has(row.section) ? row.section : "",
    seoTitle: asString(row.seo_title),
    seoDescription: asString(row.seo_description),
    seoKeywords: asString(row.seo_keywords),
    metaKeywords: asString(row.seo_keywords),
    focusKeyword: asString(row.focus_keyword),
    canonicalUrl: asString(row.canonical_url),
    metaRobots: asString(row.meta_robots, "index, follow"),
    readabilityNotes: asString(row.readability_notes),
    seoScore:
      row.seo_score === null || row.seo_score === undefined
        ? computedSeoQuality.score
        : Number(row.seo_score),
    seoStatus: asString(row.seo_status, seoBreakdown.status || computedSeoQuality.status),
    seoBreakdown,
    autoGenerated: Boolean(row.auto_generated || finalSeo.autoGenerated),
    finalSeo,
    socialTitle: asString(row.social_title),
    socialDescription: asString(row.social_description),
    socialImage: buildImageUrl(req, row.social_image) || buildImageUrl(req, row.image),
    schemaType: asString(row.schema_type, "Article"),
    schemaJson: asString(row.schema_json),
    createdAt: row.created_at,
    updatedAt: row.updated_at || row.created_at,
  };
};

const findRowsByScopedId = async (identifier) => {
  const parsed = parseScopedPostId(identifier);

  if (!parsed) {
    return [];
  }

  if (parsed.table) {
    return query(
      `SELECT '${parsed.table}' AS source_table, ${parsed.table}.* FROM ${parsed.table} WHERE id = ? LIMIT 1`,
      [parsed.id],
    );
  }

  for (const tableName of POST_TABLES) {
    const rows = await query(
      `SELECT '${tableName}' AS source_table, ${tableName}.* FROM ${tableName} WHERE id = ? LIMIT 1`,
      [parsed.id],
    );

    if (rows.length > 0) {
      return rows;
    }
  }

  return [];
};

const findTargetByScopedId = async (identifier) => {
  const rows = await findRowsByScopedId(identifier);

  if (rows.length === 0) {
    return null;
  }

  return {
    table: rows[0].source_table || getPostTableForCategory(rows[0].category),
    post: rows[0],
  };
};

const findRowsBySlug = async (slug) => {
  const rows = await query(
    `SELECT *
     FROM (${unionPostSelect()}) all_posts
     WHERE slug = ?
     LIMIT 1`,
    [slug],
  );

  return rows;
};

const slugExists = async (slug, exclude = null) => {
  const rows = await query(
    `SELECT source_table, id
     FROM (${unionPostSelect()}) all_posts
     WHERE slug = ?
     LIMIT 5`,
    [slug],
  );

  return rows.some((row) => {
    if (!exclude) {
      return true;
    }

    return row.source_table !== exclude.table || Number(row.id) !== Number(exclude.id);
  });
};

const buildSeoPersistence = (post) => {
  const finalSeo = generateFinalSeo(post);
  const seoQuality = computeSeoQuality(post, { finalSeo });

  return {
    finalSeo,
    seoQuality,
    values: {
      seoTitle: finalSeo.seoTitle || null,
      seoDescription: finalSeo.seoDescription || null,
      focusKeyword: finalSeo.focusKeyword || null,
      canonicalUrl: finalSeo.canonicalUrl || null,
      metaRobots: finalSeo.metaRobots || null,
      readabilityNotes: finalSeo.readabilityNotes || null,
      socialTitle: finalSeo.ogTitle || null,
      socialDescription: finalSeo.ogDescription || null,
      socialImage: finalSeo.ogImage || null,
      schemaType: finalSeo.schemaType || "BlogPosting",
      schemaJson: finalSeo.schemaJson || null,
      seoScore: seoQuality.score,
      seoStatus: seoQuality.status,
      seoBreakdown: JSON.stringify(seoQuality),
      autoGenerated: finalSeo.autoGenerated,
    },
  };
};

const findDuplicateSeoWarnings = async ({ postId = null, postTable = null, seoTitle, seoDescription, canonicalUrl }) => {
  const warnings = [];
  const params = [postTable || "", postId || 0];
  const idClause = postId ? " AND NOT (source_table = ? AND id = ?)" : "";

  if (!postId) {
    params.length = 0;
  }

  const runDuplicateQuery = async (field, value, label) => {
    if (!value) {
      return;
    }

    const rows = await query(
      `SELECT source_table, id, title, slug
       FROM (${unionPostSelect()}) all_posts
       WHERE ${field} = ?${idClause}
       LIMIT 5`,
      [value, ...params],
    );

    if (rows.length > 0) {
      warnings.push({
        field,
        message: `Duplicate ${label} detected`,
        matches: rows,
      });
    }
  };

  await runDuplicateQuery("seo_title", seoTitle, "title");
  await runDuplicateQuery("seo_description", seoDescription, "description");
  await runDuplicateQuery("canonical_url", canonicalUrl, "canonical URL");

  return warnings;
};

const createPost = async (req, res) => {
  try {
    await ensureBlogTables();

    const {
      title,
      slug,
      category,
      subcategory,
      content,
      tags,
      status,
      featured,
      section,
      seoTitle,
      seoDescription,
      seoKeywords,
      metaKeywords,
      focusKeyword,
      canonicalUrl,
      metaRobots,
      readabilityNotes,
      socialTitle,
      socialDescription,
      socialImage,
      schemaType,
      schemaJson,
    } = req.body;

    const normalizedTitle = (title || "").trim();
    const normalizedSlug = slugify(slug || normalizedTitle);
    const normalizedCategory = (category || "").trim();
    const normalizedSubcategory = (subcategory || "").trim();
    const normalizedContent = (content || "").trim();
    const normalizedTags = (tags || "").trim();
    const normalizedStatus = status === "published" ? "published" : "draft";
    const normalizedSection = VALID_SECTIONS.has(section) ? section : "latest";
    const normalizedSeoTitle = (seoTitle || "").trim();
    const normalizedSeoDescription = (seoDescription || "").trim();
    const normalizedSeoKeywords = (metaKeywords || seoKeywords || normalizedTags).trim();
    const normalizedFocusKeyword = (focusKeyword || "").trim();
    const normalizedCanonicalUrl = (canonicalUrl || "").trim();
    const normalizedMetaRobots = (metaRobots || "index, follow").trim();
    const normalizedReadabilityNotes = (readabilityNotes || "").trim();
    const normalizedSocialTitle = (socialTitle || normalizedSeoTitle).trim();
    const normalizedSocialDescription = (socialDescription || normalizedSeoDescription).trim();
    const normalizedSocialImage = (socialImage || "").trim();
    const normalizedSchemaType = (schemaType || "Article").trim();
    const normalizedSchemaJson = (schemaJson || "").trim();
    const normalizedFeatured =
      featured === true ||
      featured === "true" ||
      featured === "1" ||
      featured === 1;

    if (!normalizedTitle || !normalizedSlug || !normalizedCategory || !normalizedContent) {
      return res.status(400).json({
        message: "Title, slug, category, and content are required.",
      });
    }

    const imagePath = req.file ? `/uploads/posts/${req.file.filename}` : null;
    const seoContext = {
      title: normalizedTitle,
      slug: normalizedSlug,
      category: normalizedCategory,
      content: normalizedContent,
      tags: normalizedTags,
      image: imagePath,
      seoTitle: normalizedSeoTitle,
      seoDescription: normalizedSeoDescription,
      focusKeyword: normalizedFocusKeyword,
      canonicalUrl: normalizedCanonicalUrl,
      metaRobots: normalizedMetaRobots,
      readabilityNotes: normalizedReadabilityNotes,
      socialTitle: normalizedSocialTitle,
      socialDescription: normalizedSocialDescription,
      socialImage: normalizedSocialImage,
      schemaType: normalizedSchemaType,
      schemaJson: normalizedSchemaJson,
    };
    const seoPersistence = buildSeoPersistence(seoContext);
    const seoQuality = seoPersistence.seoQuality;
    const duplicateSeoWarnings = await findDuplicateSeoWarnings({
      seoTitle: seoPersistence.values.seoTitle,
      seoDescription: seoPersistence.values.seoDescription,
      canonicalUrl: seoPersistence.values.canonicalUrl,
    });

    if (duplicateSeoWarnings.length > 0) {
      seoQuality.warnings = [
        ...seoQuality.warnings,
        ...duplicateSeoWarnings.map((warning) => warning.message),
      ];
      seoQuality.duplicateWarnings = duplicateSeoWarnings;
      seoPersistence.values.seoBreakdown = JSON.stringify(seoQuality);
    }

    if (shouldBlockPublishForSeo(normalizedStatus, seoQuality)) {
      return res.status(422).json({
        message: `SEO score ${seoQuality.score} is below the publish threshold of ${seoQuality.threshold}.`,
        seoQuality,
      });
    }

    if (await slugExists(normalizedSlug)) {
      return res.status(409).json({ message: "A post with this slug already exists." });
    }

    const targetTable = getPostTableForCategory(normalizedCategory);
    const result = await query(
      `INSERT INTO ${targetTable}
        (title, slug, category, subcategory, content, image, tags, status, featured, section, seo_title, seo_description, seo_keywords, focus_keyword, canonical_url, meta_robots, readability_notes, seo_score, seo_status, seo_breakdown, auto_generated, social_title, social_description, social_image, schema_type, schema_json)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        normalizedTitle,
        normalizedSlug,
        normalizedCategory,
        normalizedSubcategory || null,
        normalizedContent,
        imagePath,
        normalizedTags || null,
        normalizedStatus,
        normalizedFeatured,
        normalizedSection,
        seoPersistence.values.seoTitle,
        seoPersistence.values.seoDescription,
        normalizedSeoKeywords || null,
        seoPersistence.values.focusKeyword,
        seoPersistence.values.canonicalUrl,
        seoPersistence.values.metaRobots,
        seoPersistence.values.readabilityNotes,
        seoPersistence.values.seoScore,
        seoPersistence.values.seoStatus,
        seoPersistence.values.seoBreakdown,
        seoPersistence.values.autoGenerated,
        seoPersistence.values.socialTitle,
        seoPersistence.values.socialDescription,
        seoPersistence.values.socialImage,
        seoPersistence.values.schemaType,
        seoPersistence.values.schemaJson,
      ],
    );

    const rows = await query(
      `SELECT '${targetTable}' AS source_table, ${targetTable}.* FROM ${targetTable} WHERE id = ?`,
      [result.insertId],
    );

    return res.status(201).json(mapPost(req, rows[0]));
  } catch (error) {
    console.error("[posts][create]", error);
    return res.status(500).json({ message: "Failed to create post." });
  }
};

const getPublishedPosts = async (req, res) => {
  try {
    await ensureBlogTables();

    const rows = await query(
      `SELECT *
       FROM (${unionPostSelect()}) all_posts
       WHERE status = 'published'
       ORDER BY featured DESC, created_at DESC`,
    );

    return res.json(rows.map((row) => mapPost(req, row)));
  } catch (error) {
    console.error("[posts][list]", error);
    return res.status(500).json({ message: "Failed to fetch posts." });
  }
};

const getPostByIdentifier = async (req, res) => {
  try {
    await ensureBlogTables();

    const { identifier } = req.params;
    const scopedId = parseScopedPostId(identifier);
    const rows = scopedId ? await findRowsByScopedId(identifier) : await findRowsBySlug(identifier);

    if (rows.length === 0) {
      return res.status(404).json({ message: "Post not found." });
    }

    const post = rows[0];
    if (post.status !== "published" && !scopedId) {
      return res.status(404).json({ message: "Post not found." });
    }

    return res.json(mapPost(req, post));
  } catch (error) {
    console.error("[posts][single]", error);
    return res.status(500).json({ message: "Failed to fetch post." });
  }
};

const getDashboardPosts = async (req, res) => {
  try {
    await ensureBlogTables();

    const rows = await query(
      `SELECT * FROM (${unionPostSelect()}) all_posts ORDER BY created_at DESC`,
    );

    return res.json(rows.map((row) => mapPost(req, row)));
  } catch (error) {
    console.error("[posts][dashboard]", error);
    return res.status(500).json({ message: "Failed to fetch dashboard posts." });
  }
};

const getPostSeo = async (req, res) => {
  try {
    await ensureBlogTables();

    const target = await findTargetByScopedId(req.params.id);
    if (!target) {
      const parsed = parseScopedPostId(req.params.id);
      if (!parsed) {
        return res.status(400).json({ message: "Invalid post id." });
      }
      return res.status(404).json({ message: "Post not found." });
    }

    const postId = target.post.id;
    if (!Number.isInteger(Number(postId)) || Number(postId) <= 0) {
      return res.status(400).json({ message: "Invalid post id." });
    }

    const finalSeo = generateFinalSeo(target.post);
    const seoQuality = computeSeoQuality(target.post, { finalSeo });
    const duplicateWarnings = await findDuplicateSeoWarnings({
      postId,
      postTable: target.table,
      seoTitle: finalSeo.seoTitle,
      seoDescription: finalSeo.seoDescription,
      canonicalUrl: finalSeo.canonicalUrl,
    });

    return res.json({
      seoQuality: {
        ...seoQuality,
        duplicateWarnings,
        warnings: [
          ...seoQuality.warnings,
          ...duplicateWarnings.map((warning) => warning.message),
        ],
      },
      finalSeo,
    });
  } catch (error) {
    console.error("[posts][seo]", error);
    return res.status(500).json({ message: "Failed to fetch SEO score." });
  }
};

const recalculatePostSeo = async (req, res) => {
  try {
    await ensureBlogTables();

    const target = await findTargetByScopedId(req.params.id);
    if (!target) {
      const parsed = parseScopedPostId(req.params.id);
      if (!parsed) {
        return res.status(400).json({ message: "Invalid post id." });
      }
      return res.status(404).json({ message: "Post not found." });
    }

    const postId = Number(target.post.id);
    if (!Number.isInteger(postId) || postId <= 0) {
      return res.status(400).json({ message: "Invalid post id." });
    }

    const seoPersistence = buildSeoPersistence(target.post);
    await query(
      `UPDATE ${target.table}
       SET seo_title = ?, seo_description = ?, focus_keyword = ?, canonical_url = ?, meta_robots = ?, readability_notes = ?, seo_score = ?, seo_status = ?, seo_breakdown = ?, auto_generated = ?, social_title = ?, social_description = ?, social_image = ?, schema_type = ?, schema_json = ?
       WHERE id = ?`,
      [
        seoPersistence.values.seoTitle,
        seoPersistence.values.seoDescription,
        seoPersistence.values.focusKeyword,
        seoPersistence.values.canonicalUrl,
        seoPersistence.values.metaRobots,
        seoPersistence.values.readabilityNotes,
        seoPersistence.values.seoScore,
        seoPersistence.values.seoStatus,
        seoPersistence.values.seoBreakdown,
        seoPersistence.values.autoGenerated,
        seoPersistence.values.socialTitle,
        seoPersistence.values.socialDescription,
        seoPersistence.values.socialImage,
        seoPersistence.values.schemaType,
        seoPersistence.values.schemaJson,
        postId,
      ],
    );

    const updatedRows = await query(
      `SELECT '${target.table}' AS source_table, ${target.table}.* FROM ${target.table} WHERE id = ? LIMIT 1`,
      [postId],
    );
    return res.json(mapPost(req, updatedRows[0]));
  } catch (error) {
    console.error("[posts][seo-recalculate]", error);
    return res.status(500).json({ message: "Failed to recalculate SEO score." });
  }
};

const getDuplicateSeo = async (_req, res) => {
  try {
    await ensureBlogTables();

    const duplicateRows = await query(
      `SELECT duplicate_type, duplicate_value, COUNT(*) AS count
       FROM (
         SELECT 'title' AS duplicate_type, seo_title AS duplicate_value FROM (${unionPostSelect()}) all_posts WHERE seo_title IS NOT NULL AND seo_title <> ''
         UNION ALL
         SELECT 'description' AS duplicate_type, seo_description AS duplicate_value FROM (${unionPostSelect()}) all_posts WHERE seo_description IS NOT NULL AND seo_description <> ''
         UNION ALL
         SELECT 'canonical' AS duplicate_type, canonical_url AS duplicate_value FROM (${unionPostSelect()}) all_posts WHERE canonical_url IS NOT NULL AND canonical_url <> ''
       ) duplicates
       GROUP BY duplicate_type, duplicate_value
       HAVING COUNT(*) > 1
       ORDER BY count DESC, duplicate_type ASC`,
    );

    return res.json({ duplicates: duplicateRows });
  } catch (error) {
    console.error("[posts][seo-duplicates]", error);
    return res.status(500).json({ message: "Failed to detect duplicate SEO metadata." });
  }
};

const updatePost = async (req, res) => {
  try {
    await ensureBlogTables();

    const target = await findTargetByScopedId(req.params.id);
    if (!target) {
      const parsed = parseScopedPostId(req.params.id);
      if (!parsed) {
        return res.status(400).json({ message: "Invalid post id." });
      }
      return res.status(404).json({ message: "Post not found." });
    }

    const postId = Number(target.post.id);
    if (!Number.isInteger(postId) || postId <= 0) {
      return res.status(400).json({ message: "Invalid post id." });
    }

    const existingPost = target.post;
    const {
      title,
      slug,
      category,
      subcategory,
      content,
      tags,
      status,
      featured,
      section,
      seoTitle,
      seoDescription,
      seoKeywords,
      metaKeywords,
      focusKeyword,
      canonicalUrl,
      metaRobots,
      readabilityNotes,
      socialTitle,
      socialDescription,
      socialImage,
      schemaType,
      schemaJson,
    } = req.body;

    const normalizedTitle = (title || existingPost.title || "").trim();
    const normalizedSlug = slugify(slug || normalizedTitle);
    const normalizedCategory = (category || existingPost.category || "").trim();
    const normalizedSubcategory =
      (subcategory !== undefined ? subcategory : existingPost.subcategory || "").trim();
    const normalizedContent = (content || existingPost.content || "").trim();
    const normalizedTags =
      (tags !== undefined ? tags : existingPost.tags || "").toString().trim();
    const normalizedStatus = status === "published" ? "published" : "draft";
    const normalizedSection = VALID_SECTIONS.has(section) ? section : existingPost.section || "latest";
    const normalizedSeoTitle =
      (seoTitle !== undefined ? seoTitle : existingPost.seo_title || "")
        .toString()
        .trim();
    const normalizedSeoDescription =
      (seoDescription !== undefined
        ? seoDescription
        : existingPost.seo_description || "")
        .toString()
        .trim();
    const normalizedSeoKeywords =
      (metaKeywords !== undefined
        ? metaKeywords
        : seoKeywords !== undefined
        ? seoKeywords
        : existingPost.seo_keywords || normalizedTags)
        .toString()
        .trim();
    const normalizedFocusKeyword =
      (focusKeyword !== undefined ? focusKeyword : existingPost.focus_keyword || "")
        .toString()
        .trim();
    const normalizedCanonicalUrl =
      (canonicalUrl !== undefined ? canonicalUrl : existingPost.canonical_url || "")
        .toString()
        .trim();
    const normalizedMetaRobots =
      (metaRobots !== undefined ? metaRobots : existingPost.meta_robots || "index, follow")
        .toString()
        .trim();
    const normalizedReadabilityNotes =
      (readabilityNotes !== undefined ? readabilityNotes : existingPost.readability_notes || "")
        .toString()
        .trim();
    const normalizedSocialTitle =
      (socialTitle !== undefined
        ? socialTitle
        : existingPost.social_title || normalizedSeoTitle)
        .toString()
        .trim();
    const normalizedSocialDescription =
      (socialDescription !== undefined
        ? socialDescription
        : existingPost.social_description || normalizedSeoDescription)
        .toString()
        .trim();
    const normalizedSocialImage =
      (socialImage !== undefined ? socialImage : existingPost.social_image || "")
        .toString()
        .trim();
    const normalizedSchemaType =
      (schemaType !== undefined ? schemaType : existingPost.schema_type || "Article")
        .toString()
        .trim();
    const normalizedSchemaJson =
      (schemaJson !== undefined ? schemaJson : existingPost.schema_json || "")
        .toString()
        .trim();
    const normalizedFeatured =
      featured === true ||
      featured === "true" ||
      featured === "1" ||
      featured === 1;

    if (!normalizedTitle || !normalizedSlug || !normalizedCategory || !normalizedContent) {
      return res.status(400).json({
        message: "Title, slug, category, and content are required.",
      });
    }

    const imagePath = req.file ? `/uploads/posts/${req.file.filename}` : existingPost.image;
    const seoContext = {
      title: normalizedTitle,
      slug: normalizedSlug,
      category: normalizedCategory,
      content: normalizedContent,
      tags: normalizedTags,
      image: imagePath,
      seoTitle: normalizedSeoTitle,
      seoDescription: normalizedSeoDescription,
      focusKeyword: normalizedFocusKeyword,
      canonicalUrl: normalizedCanonicalUrl,
      metaRobots: normalizedMetaRobots,
      readabilityNotes: normalizedReadabilityNotes,
      socialTitle: normalizedSocialTitle,
      socialDescription: normalizedSocialDescription,
      socialImage: normalizedSocialImage,
      schemaType: normalizedSchemaType,
      schemaJson: normalizedSchemaJson,
      createdAt: existingPost.created_at,
      updatedAt: existingPost.updated_at || existingPost.created_at,
    };
    const seoPersistence = buildSeoPersistence(seoContext);
    const seoQuality = seoPersistence.seoQuality;
    const duplicateSeoWarnings = await findDuplicateSeoWarnings({
      postId,
      postTable: target.table,
      seoTitle: seoPersistence.values.seoTitle,
      seoDescription: seoPersistence.values.seoDescription,
      canonicalUrl: seoPersistence.values.canonicalUrl,
    });

    if (duplicateSeoWarnings.length > 0) {
      seoQuality.warnings = [
        ...seoQuality.warnings,
        ...duplicateSeoWarnings.map((warning) => warning.message),
      ];
      seoQuality.duplicateWarnings = duplicateSeoWarnings;
      seoPersistence.values.seoBreakdown = JSON.stringify(seoQuality);
    }

    if (shouldBlockPublishForSeo(normalizedStatus, seoQuality)) {
      return res.status(422).json({
        message: `SEO score ${seoQuality.score} is below the publish threshold of ${seoQuality.threshold}.`,
        seoQuality,
      });
    }

    if (await slugExists(normalizedSlug, { table: target.table, id: postId })) {
      return res.status(409).json({ message: "A post with this slug already exists." });
    }

    if (req.file) {
      if (existingPost.image) {
        const absoluteOldPath = path.join(__dirname, "..", existingPost.image.replace(/^\/+/, ""));
        if (fs.existsSync(absoluteOldPath)) {
          fs.unlinkSync(absoluteOldPath);
        }
      }
    }

    const nextTable = getPostTableForCategory(normalizedCategory);
    await query(
      `UPDATE ${target.table}
       SET title = ?, slug = ?, category = ?, subcategory = ?, content = ?, image = ?, tags = ?, status = ?, featured = ?, section = ?, seo_title = ?, seo_description = ?, seo_keywords = ?, focus_keyword = ?, canonical_url = ?, meta_robots = ?, readability_notes = ?, seo_score = ?, seo_status = ?, seo_breakdown = ?, auto_generated = ?, social_title = ?, social_description = ?, social_image = ?, schema_type = ?, schema_json = ?
       WHERE id = ?`,
      [
        normalizedTitle,
        normalizedSlug,
        normalizedCategory,
        normalizedSubcategory || null,
        normalizedContent,
        imagePath,
        normalizedTags || null,
        normalizedStatus,
        normalizedFeatured,
        normalizedSection,
        seoPersistence.values.seoTitle,
        seoPersistence.values.seoDescription,
        normalizedSeoKeywords || null,
        seoPersistence.values.focusKeyword,
        seoPersistence.values.canonicalUrl,
        seoPersistence.values.metaRobots,
        seoPersistence.values.readabilityNotes,
        seoPersistence.values.seoScore,
        seoPersistence.values.seoStatus,
        seoPersistence.values.seoBreakdown,
        seoPersistence.values.autoGenerated,
        seoPersistence.values.socialTitle,
        seoPersistence.values.socialDescription,
        seoPersistence.values.socialImage,
        seoPersistence.values.schemaType,
        seoPersistence.values.schemaJson,
        postId,
      ],
    );

    if (nextTable !== target.table) {
      const movedRows = await query(
        `SELECT * FROM ${target.table} WHERE id = ? LIMIT 1`,
        [postId],
      );
      const movedPost = movedRows[0];
      const duplicateInTarget = await query(
        `SELECT id FROM ${nextTable} WHERE slug = ? LIMIT 1`,
        [movedPost.slug],
      );

      if (duplicateInTarget.length === 0) {
        const insertResult = await query(
          `INSERT INTO ${nextTable}
            (title, slug, category, subcategory, content, image, tags, status, featured, section, seo_title, seo_description, seo_keywords, focus_keyword, canonical_url, meta_robots, readability_notes, seo_score, seo_status, seo_breakdown, auto_generated, social_title, social_description, social_image, schema_type, schema_json, created_at, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            movedPost.title,
            movedPost.slug,
            movedPost.category,
            movedPost.subcategory,
            movedPost.content,
            movedPost.image,
            movedPost.tags,
            movedPost.status,
            movedPost.featured,
            movedPost.section,
            movedPost.seo_title,
            movedPost.seo_description,
            movedPost.seo_keywords,
            movedPost.focus_keyword,
            movedPost.canonical_url,
            movedPost.meta_robots,
            movedPost.readability_notes,
            movedPost.seo_score,
            movedPost.seo_status,
            movedPost.seo_breakdown,
            movedPost.auto_generated,
            movedPost.social_title,
            movedPost.social_description,
            movedPost.social_image,
            movedPost.schema_type,
            movedPost.schema_json,
            movedPost.created_at,
            movedPost.updated_at || movedPost.created_at,
          ],
        );
        await query(`DELETE FROM ${target.table} WHERE id = ?`, [postId]);
        const rows = await query(
          `SELECT '${nextTable}' AS source_table, ${nextTable}.* FROM ${nextTable} WHERE id = ? LIMIT 1`,
          [insertResult.insertId],
        );
        return res.json(mapPost(req, rows[0]));
      }
    }

    const rows = await query(
      `SELECT '${target.table}' AS source_table, ${target.table}.* FROM ${target.table} WHERE id = ? LIMIT 1`,
      [postId],
    );
    return res.json(mapPost(req, rows[0]));
  } catch (error) {
    console.error("[posts][update]", error);
    return res.status(500).json({ message: "Failed to update post." });
  }
};

const deletePost = async (req, res) => {
  try {
    await ensureBlogTables();

    const target = await findTargetByScopedId(req.params.id);
    if (!target) {
      const parsed = parseScopedPostId(req.params.id);
      if (!parsed) {
        return res.status(400).json({ message: "Invalid post id." });
      }
      return res.status(404).json({ message: "Post not found." });
    }

    const postId = Number(target.post.id);
    if (!Number.isInteger(postId) || postId <= 0) {
      return res.status(400).json({ message: "Invalid post id." });
    }

    const existingPost = target.post;
    await query(`DELETE FROM ${target.table} WHERE id = ?`, [postId]);

    if (existingPost.image) {
      const absoluteImagePath = path.join(__dirname, "..", existingPost.image.replace(/^\/+/, ""));
      if (fs.existsSync(absoluteImagePath)) {
        fs.unlinkSync(absoluteImagePath);
      }
    }

    return res.json({ message: "Post deleted successfully." });
  } catch (error) {
    console.error("[posts][delete]", error);
    return res.status(500).json({ message: "Failed to delete post." });
  }
};

module.exports = {
  createPost,
  getPublishedPosts,
  getPostByIdentifier,
  getDashboardPosts,
  getPostSeo,
  recalculatePostSeo,
  getDuplicateSeo,
  updatePost,
  deletePost,
};
