import http from "./http";

const stripHtml = (value = "") => value.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
const hasValue = (value) => value !== undefined && value !== null && String(value).trim() !== "";
const pickValue = (...values) => {
  const match = values.find((value) => hasValue(value));
  return match === undefined ? "" : String(match);
};

const normalizePost = (post = {}) => {
  const tags = Array.isArray(post.tags) ? post.tags.join(", ") : post.tags || "";
  const excerpt = stripHtml(post.content || "").slice(0, 180);
  const seoTitle = pickValue(post.seoTitle, post.seo_title);
  const seoDescription = pickValue(
    post.seoDescription,
    post.seo_description,
    post.description,
  );
  const seoKeywords = pickValue(post.seoKeywords, post.seo_keywords, post.metaKeywords, tags);

  return {
    ...post,
    seoTitle,
    seoDescription,
    seoKeywords,
    metaKeywords: pickValue(post.metaKeywords, post.seoKeywords, post.seo_keywords, tags),
    focusKeyword: pickValue(post.focusKeyword, post.focus_keyword),
    canonicalUrl: pickValue(post.canonicalUrl, post.canonical_url),
    metaRobots: pickValue(post.metaRobots, post.meta_robots, "index, follow"),
    readabilityNotes: pickValue(post.readabilityNotes, post.readability_notes),
    socialTitle: pickValue(post.socialTitle, post.social_title, seoTitle),
    socialDescription: pickValue(
      post.socialDescription,
      post.social_description,
      seoDescription,
    ),
    socialImage: pickValue(post.socialImage, post.social_image, post.image),
    schemaType: pickValue(post.schemaType, post.schema_type, "Article"),
    schemaJson: pickValue(post.schemaJson, post.schema_json),
    seoScore:
      post.seoScore !== undefined && post.seoScore !== null
        ? Number(post.seoScore)
        : post.seo_score !== undefined && post.seo_score !== null
        ? Number(post.seo_score)
        : null,
    seoStatus: pickValue(post.seoStatus, post.seo_status),
    seoBreakdown: post.seoBreakdown || post.seo_breakdown || null,
    autoGenerated: Boolean(post.autoGenerated ?? post.auto_generated),
    finalSeo: post.finalSeo || post.final_seo || null,
    description: pickValue(post.description, seoDescription, excerpt),
  };
};

export const FALLBACK_BLOG_POSTS = [
  {
    id: "fallback-featured",
    title: "Marketing Insight Preview",
    slug: "marketing-insight-preview",
    category: "Insights",
    subcategory: "Preview",
    content:
      "<p>This preview post keeps the blog layout populated while live posts are unavailable.</p><p>Once the MySQL server and API are running again, published posts will replace this placeholder automatically.</p>",
    image: "",
    tags: ["preview", "blog"],
    status: "published",
    featured: true,
    section: "featured",
    createdAt: "2026-05-10T00:00:00.000Z",
    description:
      "This preview post keeps the blog layout populated while live posts are unavailable.",
    isFallback: true,
  },
  {
    id: "fallback-editor-1",
    title: "Building a Practical Content Calendar",
    slug: "building-a-practical-content-calendar",
    category: "Strategy",
    subcategory: "",
    content:
      "<p>A steady publishing rhythm helps teams plan campaigns, coordinate creative work, and keep audiences engaged across channels.</p>",
    image: "",
    tags: ["strategy", "content"],
    status: "published",
    featured: false,
    section: "editor",
    createdAt: "2026-05-09T00:00:00.000Z",
    isFallback: true,
  },
  {
    id: "fallback-editor-2",
    title: "Using Analytics to Shape Better Campaigns",
    slug: "using-analytics-to-shape-better-campaigns",
    category: "Analytics",
    subcategory: "",
    content:
      "<p>Clear reporting turns campaign performance into useful decisions about budget, audience, messaging, and creative direction.</p>",
    image: "",
    tags: ["analytics", "campaigns"],
    status: "published",
    featured: false,
    section: "editor",
    createdAt: "2026-05-08T00:00:00.000Z",
    isFallback: true,
  },
  {
    id: "fallback-latest-1",
    title: "Creative Signals Worth Reviewing Weekly",
    slug: "creative-signals-worth-reviewing-weekly",
    category: "Creative",
    subcategory: "",
    content:
      "<p>Reviewing hooks, formats, and audience response every week helps marketing teams keep useful ideas moving forward.</p>",
    image: "",
    tags: ["creative", "testing"],
    status: "published",
    featured: false,
    section: "latest",
    createdAt: "2026-05-07T00:00:00.000Z",
    isFallback: true,
  },
  {
    id: "fallback-latest-2",
    title: "Simple Ways to Improve Social Proof",
    slug: "simple-ways-to-improve-social-proof",
    category: "Social Media",
    subcategory: "",
    content:
      "<p>Case studies, testimonials, and clear proof points make brand promises easier for customers to trust.</p>",
    image: "",
    tags: ["social", "trust"],
    status: "published",
    featured: false,
    section: "latest",
    createdAt: "2026-05-06T00:00:00.000Z",
    isFallback: true,
  },
  {
    id: "fallback-latest-3",
    title: "Turning Research Into Useful Content",
    slug: "turning-research-into-useful-content",
    category: "Research",
    subcategory: "",
    content:
      "<p>Strong research can become blog articles, sales enablement, short posts, and campaign ideas without losing its core message.</p>",
    image: "",
    tags: ["research", "content"],
    status: "published",
    featured: false,
    section: "latest",
    createdAt: "2026-05-05T00:00:00.000Z",
    isFallback: true,
  },
];

export const FALLBACK_CATEGORIES = [
  {
    id: "fallback-category-branding",
    name: "Branding",
    subcategories: [
      { id: "fallback-subcategory-brand-identity", name: "Brand Identity" },
      { id: "fallback-subcategory-positioning", name: "Positioning" },
    ],
  },
  {
    id: "fallback-category-marketing",
    name: "Marketing",
    subcategories: [
      { id: "fallback-subcategory-social-media", name: "Social Media" },
      { id: "fallback-subcategory-campaigns", name: "Campaigns" },
    ],
  },
  {
    id: "fallback-category-strategy",
    name: "Strategy",
    subcategories: [
      { id: "fallback-subcategory-content", name: "Content Strategy" },
      { id: "fallback-subcategory-growth", name: "Growth" },
    ],
  },
  {
    id: "fallback-category-technology",
    name: "Technology",
    subcategories: [
      { id: "fallback-subcategory-analytics", name: "Analytics" },
      { id: "fallback-subcategory-automation", name: "Automation" },
    ],
  },
];

export const getPublishedPosts = async () => {
  const { data } = await http.get("/api/posts");
  return Array.isArray(data) ? data.map(normalizePost) : [];
};

export const getDashboardPosts = async () => {
  const { data } = await http.get("/api/dashboard/posts");
  return Array.isArray(data) ? data.map(normalizePost) : [];
};

export const getPostBySlug = async (slug) => {
  const { data } = await http.get(`/api/posts/${slug}`);
  return normalizePost(data);
};

export const getPostById = async (id) => {
  const { data } = await http.get(`/api/posts/${id}`);
  return normalizePost(data);
};

export const getCategories = async () => {
  const { data } = await http.get("/api/categories");
  return Array.isArray(data) ? data : [];
};

export const createPost = async (payload) => {
  const formData = new FormData();

  Object.entries(payload).forEach(([key, value]) => {
    if (value !== undefined && value !== null && value !== "") {
      formData.append(key, value);
    }
  });

  const { data } = await http.post("/api/posts", formData, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });

  return data;
};

export const updatePost = async (id, payload) => {
  const formData = new FormData();

  Object.entries(payload).forEach(([key, value]) => {
    if (value !== undefined && value !== null && value !== "") {
      formData.append(key, value);
    }
  });

  const { data } = await http.put(`/api/posts/${id}`, formData, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });

  return data;
};

export const deletePost = async (id) => {
  const { data } = await http.delete(`/api/posts/${id}`);
  return data;
};

export const getPostSeo = async (id) => {
  const { data } = await http.get(`/api/posts/${id}/seo`);
  return data;
};

export const recalculatePostSeo = async (id) => {
  const { data } = await http.post(`/api/posts/${id}/seo/recalculate`);
  return normalizePost(data);
};

export const getSeoDuplicates = async () => {
  const { data } = await http.get("/api/dashboard/seo/duplicates");
  return data?.duplicates || [];
};
