on: push
name:  Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name:  Get latest code
      uses: actions/checkout@v4
    
    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.curatedgallery.org
        username: AdminB@blucomtechnologies.com
        password: ${{ secrets.FTP_PASSWORDADMINB }}
        server-dir: '/home/ashfaqahmed/public_html/'
